### ISSUE TITLE
I got cuDNN error. what versions of cuda and cudnn of this code are used?

### ISSUE THREAD

**Issue by ChuanMeng** [qkaren/converse_reading_cmr#6]
Traceback (most recent call last):
  File "train.py", line 203, in <module>
    main()
  File "train.py", line 65, in main
    model.cuda()  
  File "/home/cmr/model/src/model.py", line 513, in cuda
    self.network.cuda()
  File "/home/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 260, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/home/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/home/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/anaconda3/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 117, in _apply
    self.flatten_parameters()
  File "/home/anaconda3/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 113, in flatten_parameters
    self.batch_first, bool(self.bidirectional))
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

So I guess it's the problem of versions of cuda and cudnn . 
I would appreiciate if you can give a explanation. : )

**Comment by qkaren** [comment]
Hi ChuanMeng, 

Did you try to pull our published docker: allenlao/pytorch-allennlp-rt ?
