### ISSUE TITLE
KeyError: 'skip_tokens'

### ISSUE THREAD

**Issue by ChuanMeng** [qkaren/converse_reading_cmr#7]
Traceback (most recent call last):
  File "train.py", line 203, in <module>
    main()
  File "train.py", line 119, in main
    pred_output, full_output)
  File "/storage2/cmr/model/train_util.py", line 63, in check
    prediction, prediction_topks = model.predict(batch)
  File "/storage2/cmr/model/src/model.py", line 379, in predict
    if self.opt['skip_tokens']:
KeyError: 'skip_tokens'

I find the config.py only contains 'skip_tokens_file' and doesn't have 'skip_tokens'. It is a mistake?

**Comment by Arij-Aladel** [comment]
yes it is a mistake
